# Generated by Django 5.0.2 on 2024-02-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inboxi", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="topics",
            field=models.ManyToManyField(
                through="inboxi.Subscription", to="inboxi.topic"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="subscribers",
            field=models.ManyToManyField(
                through="inboxi.Subscription", to="inboxi.subscriber"
            ),
        ),
    ]
